### PR TITLE
Added record handler feature

### PR DESCRIPTION
**Pull request by atarassov-ttd**
- gives finer control over memory allocations and how the received data is interpreted
- allows customising how received records/bins are handled
- provides hook for custom parsing of bin values directly from receive buffer
- enables the handler to specify that bin values do not need to be saved into the record's bins dictionary

### CODE REVIEW

**Comment by BrianNichols** [comment]
I'm currently busy with other tasks, so I will review this when I get a chance. Also, I will eventually benchmark the default singleton case against previous client versions to ensure that no performance regressions occurred.

**Comment by atarassov-ttd** [comment]
I've redone the changes to use a record parser interface instead with moving `Command.ParseRecord()` to the default implementation of the interface. I've also added a simple function to extract basic information from protocol fields. Hopefully this addresses your goals.

**Comment by BrianNichols** [comment]
Your pull request has been accepted into the stage branch with some minor modifications.  It will appear in the main branch in the next C# client release.

**Comment by atarassov-ttd** [comment]
Thanks! When would you expect the next release to come out?

Shall I close this PR now given you have it in the staging branch already?

**Comment by BrianNichols** [comment]
C# client 4.2.4 released.

**Pull request closed without merging**
