### PR TITLE
Add byte rate metrics

### LINKED ISSUE #109: ConnectionStats.Bytes{Read/Written}
What do you think of adding bytes read and written to the socket in the `ConnectionStats` object? I could work on the PR if you're interested.

### PR DESCRIPTION
**Pull request by verdie-g**
For now it's only added to AsyncCommand. Closes #109.

### CODE REVIEW

**Comment by shannonklaus** [comment]
@verdie-g I have work in progress for adding a metrics feature to the client. There are two parts to it, one of them is the current info in ClusterStats and the second part is extended metrics including transaction count and latency buckets on a per node basis. I can add byte rate metrics to the extended metrics. Since what you are suggesting requires two atomic operations per transaction we don't want to have it enabled by default.

**Comment by shannonklaus** [comment]
No, we would still like to wait until the metrics as I described are implemented and the bytes sent/received should only be enabled when metrics are enabled by the user.

**Comment by verdie-g** [comment]
Got it. Would you have an idea when these metrics could be available?

**Comment by shannonklaus** [comment]
I am currently planning on including it in the April release, which should be toward the end of April.

**Pull request closed without merging**
