### PR TITLE
Adding IRecordSet and IResultSet derived interfaces for easier usage …

### PR DESCRIPTION
**Pull request by Jac21**
…within mocking libraries

Issue reference - #45

### CODE REVIEW

**Comment by BrianNichols** [comment]
Your pull request has been accepted with some minor changes.  The namespace for IRecordSet/IResultSet was changed to "Aerospike.Client" and the .NET Core project added links for those files.

These changes will appear in the next release of the C# client.

**Comment by BrianNichols** [comment]
C# client 3.9.2 has been released:

https://www.aerospike.com/download/client/csharp/3.9.2/

**Comment by Jac21** [comment]
Thanks!

**Comment by Vidz51** [comment]
is this change in java as well? I want to mock RecordSet. cant find any leads.

**Comment by Jac21** [comment]
> is this change in java as well? I want to mock RecordSet. cant find any leads.

I only covered the C# client within my enhancement request and subsequent PR. I'm sure a PR for the Java client will look virtually identical if you wanted to get that implemented 😄

**Comment by Vidz51** [comment]
Sure would love to.
On it.

**Pull request closed without merging**
